apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-sync
  namespace: laravel
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-sync
  template:
    metadata:
      labels:
        app: git-sync
    spec:
      initContainers:
        - name: init-exechook
          image: busybox
          command:
            - sh
            - -c
            - |
              if [ -f /scripts/exechook.sh ]; then
                cp /scripts/exechook.sh /workdir/exechook.sh
                chmod +x /workdir/exechook.sh
              else
                echo "Script not found in /scripts" && exit 1
              fi
          volumeMounts:
            - name: exechook-script-volume
              mountPath: /scripts
            - name: workdir-volume
              mountPath: /workdir
      containers:
        # Git Sync 容器
        - name: git-sync
          image: k8s.gcr.io/git-sync/git-sync:v4.0.0
          args:
            - --repo=https://github.com/laravel/laravel
            - --depth=1
            - --period=60s
            - --ref=11.x
            - --root=/var/www/
            - --exechook-command=/bin/sh /workdir/exechook.sh
          volumeMounts:
            - name: app-code
              mountPath: /var/www/
            - name: workdir-volume
              mountPath: /workdir
      volumes:
        - name: app-code
          persistentVolumeClaim:
            claimName: laravel-code-pvc
        - name: exechook-script-volume
          configMap:
            name: git-sync-exechook-configmap
        - name: workdir-volume
          emptyDir: {}