apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-sync
  namespace: laravel
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-sync
  template:
    metadata:
      labels:
        app: git-sync
    spec:
      containers:
        # Git Sync 容器
        - name: git-sync
          image: k8s.gcr.io/git-sync/git-sync:v4.0.0
          args:
            - --repo=https://github.com/laravel/laravel
            - --depth=1
            - --period=60s
            - --ref=11.x
            - --root=/var/www/
          volumeMounts:
            - name: app-code
              mountPath: /var/www/
        # Sidecar 容器：執行安裝邏輯
        - name: installer
          image: php:8.3.16-fpm  # 替換成包含必要工具的映像
          command:
            - /bin/sh
            - -c
            - |
              apt-get update && apt-get install -y --no-install-recommends git \
              && curl -sS https://getcomposer.org/installer | php \
              && mv composer.phar /usr/local/bin/composer \
              && set -e
              SYNC_DIR="/var/www/laravel"
              HASH_FILE="${SYNC_DIR}/.last_sync_hash"

              echo "Installer Sidecar started..."
              while true; do
                # 確保同步的程式碼目錄存在
                if [ ! -d "$SYNC_DIR" ]; then
                  echo "Error: Sync directory $SYNC_DIR does not exist. Retrying..."
                  sleep 10
                  continue
                fi

                # 獲取最新的提交哈希
                cd $SYNC_DIR
                CURRENT_HASH=$(git rev-parse HEAD)

                # 初始化哈希檔案
                if [ ! -f "$HASH_FILE" ]; then
                  echo "Initializing hash tracking..."
                  echo $CURRENT_HASH > $HASH_FILE
                  echo "Hash file created with hash: $CURRENT_HASH"
                fi

                # 讀取上次的哈希
                LAST_HASH=$(cat $HASH_FILE)

                # 比對哈希
                if [ "$CURRENT_HASH" != "$LAST_HASH" ]; then
                  echo "Hash has changed! Previous: $LAST_HASH, Current: $CURRENT_HASH"

                  # 執行安裝邏輯
                  cd /var/www/laravel
                  echo "Running installation tasks..."
                  composer install --no-dev --optimize-autoloader
                  #npm install
                  #gulp build

                  # 更新哈希檔案
                  echo $CURRENT_HASH > $HASH_FILE
                  echo "Hash updated to: $CURRENT_HASH"
                else
                  echo "No changes detected. Current hash: $CURRENT_HASH"
                fi

                sleep 60  # 等待下一輪檢查
              done
          volumeMounts:
            - name: app-code
              mountPath: /var/www/
      volumes:
        - name: app-code
          persistentVolumeClaim:
            claimName: laravel-code-pvc