apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-sync
  namespace: laravel
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-sync
  template:
    metadata:
      labels:
        app: git-sync
    spec:
      containers:
        # Git Sync 容器
        - name: git-sync
          image: k8s.gcr.io/git-sync/git-sync:v4.0.0
          args:
            - --repo=https://github.com/laravel/laravel
            - --depth=1
            - --period=60s
            - --ref=11.x
            - --root=/var/www/
            - "--exechook-command=/scripts/restart-pod.sh"
          volumeMounts:
            - name: app-code
              mountPath: /var/www/
            - name: scripts
              mountPath: /scripts
        # Sidecar 容器 (執行 kubectl 重啟)
        - name: kubectl-sidecar
          image: bitnami/kubectl:latest
          command:
            - /bin/bash
            - -c
            - |
              echo "Sidecar ready for restarting pods."
              while true; do sleep 3600; done
          volumeMounts:
            - name: scripts
              mountPath: /scripts 
      volumes:
        - name: app-code
          persistentVolumeClaim:
            claimName: laravel-code-pvc
        - name: scripts
          configMap:
            name: git-sync-scripts