apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-sync
  namespace: laravel
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-sync
  template:
    metadata:
      labels:
        app: git-sync
    spec:
      initContainers:
        # 檢查並初始化 Git 資料夾
        - name: git-init
          image: alpine/git
          command:
            - /bin/sh
            - -c
            - |
              if [ ! -d "/var/www/laravel/.git" ]; then
                echo "Cloning repository..."
                git clone https://github.com/laravel/laravel /var/www/laravel && \
                cd /var/www/laravel && git checkout 5.1;
              else
                echo "Updating repository..."
                cd /var/www/laravel && git fetch origin ;
              fi
          volumeMounts:
            - name: app-code
              mountPath: /var/www/

      containers:
        - name: npm-cap
          image: flymaple628/npm-cap-8.6.0:1.0
          workingDir: /var/www/laravel
          command: ["/bin/sh", "-c"]
          args:
            - |
              npm install --force --yes && \
              echo "NPM install complete. Keeping container alive..." && \
              tail -f /dev/null
          tty: true
          volumeMounts:
            - name: app-code
              mountPath: /var/www
        - name: fpm
          image: flymaple628/php-fpm-7.0:1.0
          env:
            - name: COMPOSER_ALLOW_SUPERUSER
              value: "1"
          workingDir: /var/www/laravel
          command: ["/bin/sh", "-c"]
          args:
            - |
              composer install && php-fpm
          volumeMounts:
            - name: app-code
              mountPath: /var/www
      volumes:
        - name: app-code
          persistentVolumeClaim:
            claimName: laravel-code-pvc