apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-sync
  namespace: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-sync
  template:
    metadata:
      labels:
        app: git-sync
    spec:
      containers:
        - name: git-sync
          image: k8s.gcr.io/git-sync/git-sync:v4.0.0
          env:
            - name: GITSYNC_REPO
              value: "https://github.com/laravel/laravel.git"
            - name: GITSYNC_BRANCH
              value: "11.x"
            - name: GITSYNC_DEST
              value: "/repo"
            - name: GITSYNC_WAIT
              value: "30"
          volumeMounts:
            - name: app-code
              mountPath: /var/www
      volumes:
        - name: app-code
          persistentVolumeClaim:
            claimName: laravel-code-pvc