apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-sync
  namespace: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-sync
  template:
    metadata:
      labels:
        app: git-sync
    spec:
      containers:
        - name: git-sync
          image: k8s.gcr.io/git-sync/git-sync:v4.0.0
          args:
            - --repo=https://github.com/laravel/laravel
            - --depth=1
            - --period=60s
            - --ref=11.x
            - --root=/var/www/laravel
          volumeMounts:
            - name: app-code
              mountPath: /var/www/laravel
      volumes:
        - name: app-code
          persistentVolumeClaim:
            claimName: laravel-code-pvc