apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-sync
  namespace: laravel
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-sync
  template:
    metadata:
      labels:
        app: git-sync
    spec:
      initContainers:
        - name: init-exechook
          image: busybox
          command:
            - sh
            - -c
            - |
              cp /scripts/exechook.sh /var/www/exechook.sh && chmod +x /var/www/exechook.sh
          volumeMounts:
            - name: app-code
              mountPath: /var/www/
            - name: exechook-script-volume # 修改此名稱與 volumes 一致
              mountPath: /scripts
              readOnly: true
      containers:
        # Git Sync 容器
        - name: git-sync
          image: k8s.gcr.io/git-sync/git-sync:v4.0.0
          args:
            - --repo=https://github.com/laravel/laravel
            - --depth=1
            - --period=60s
            - --ref=11.x
            - --root=/var/www/
            - --exechook-command=exechook.sh
          volumeMounts:
            - name: app-code
              mountPath: /var/www/
      volumes:
        - name: app-code
          persistentVolumeClaim:
            claimName: laravel-code-pvc
        - name: exechook-script-volume # 修改此名稱與 volumeMounts 一致
          configMap:
            name: git-sync-exechook-configmap