apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
  namespace: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
        - name: php-fpm
          image: jkaninda/laravel-php-fpm:latest
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: app-code
              mountPath: /var/www/
            - name: shared-cache
              mountPath: /var/www/storage
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: app-code
              mountPath: /var/www/
      volumes:
        - name: app-code
          persistentVolumeClaim:
            claimName: laravel-code-pvc
        - name: shared-cache
          emptyDir: {}