apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
  namespace: laravel
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
        - name: php-fpm
          image: jkaninda/laravel-php-fpm:latest
          workingDir: /var/www/laravel
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: app-code
              mountPath: /var/www
            - name: shared-cache
              mountPath: /var/www/laravel/storage
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - "composer install && npm install && php artisan migrate --force"  # 安裝 Composer 依賴和 NPM 包

        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: app-code
              mountPath: /var/www/laravel/public
      volumes:
        - name: app-code
          persistentVolumeClaim:
            claimName: laravel-code-pvc
        - name: shared-cache
          emptyDir: {}